honeypot:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  cowrie:
    image:
      repository: cowrie/cowrie
      tag: latest
    imagePullPolicy: Always

kubernetesClusterDomain: cluster.local

service:
  type: LoadBalancer
  port: 22
  targetPort: 2222
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

serviceAccount:
  create: true
  name: honeypot-sa
  annotations: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
