apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-honeypot-access
spec:
  podSelector:
    matchLabels:
      app: {{ include "honeypot.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0  # 🔁 Replace with allowlisted CIDR for real usage
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
